apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace | default "microservices" }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  ORDER_EVENTS_TOPIC: {{ .Values.kafka.topics.orderEvents | quote }}
  PAYMENT_EVENTS_TOPIC: {{ .Values.kafka.topics.paymentEvents | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
