apiVersion: v1
kind: Secret
metadata:
  name: order-payment-secrets
  namespace: microservices
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres" | base64
  order-db-password: cG9zdGdyZXM=
  payment-db-password: cG9zdGdyZXM=
  kafka-password: ""
  redis-password: ""
